name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: windows-latest
    name: CI
    steps:
      - uses: actions/checkout@v3

      - name: Check CMake version
        run: cmake --version

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Cache build/
        id: cache-build
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-build

      - name: Generate CMake project
        run: cmake -S. -Bbuild -G "Visual Studio 17 2022" -DCMAKE_CONFIGURATION_TYPES=Release 

      - name: Build 64bit release DLL
        run: cmake --build build --config Release --target ALL_BUILD

      - name: Check if DLL got built
        run: if (-Not (Test-Path -path "build/Release/MDVW_Controller.dll")) {throw 1}

      - name: Rename DLL to MDVW_Controller-dev-{GITHUB_SHA}.dll
        run: |
          del MDVW_Controller-dev-*.dll
          ren MDVW_Controller.dll MDVW_Controller-dev-${{github.sha}}.dll
        working-directory: build/Release/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: build/Release/MDVW_Controller-dev-*.dll
